### ISSUE TITLE
`combined_diff` appears to mix up open/close tags

### ISSUE THREAD

**Issue by Mr0grog** [anastasia/htmldiffer#27]
I just tried this scenario where the text is the same, but the element containing it is different:

```py
d = diff.HTMLDiffer('<h1>whatever</h1>', '<div>whatever</div>')
d.combined_diff
# <h1><div>whatever</h1></div>
```

I’m not totally sure what the ideal output here would be, but it would at least be good if elements properly contained each other, so the `<h1>` contained the `<div>` or vice-versa.

**Comment by anastasia** [comment]
html tag restructuring now happens via BeautifulSoup.
The correct answer is to rewrite SequenceMatcher to be HTML aware, but that will have to wait for some version 2...
now:
```
d = diff.HTMLDiffer('<h1>whatever</h1>', '<div>whatever</div>')
d.combined_diff
<h1 class="htmldiffer-tag-change_delete"><div class="htmldiffer-tag-change_insert">whatever</div></h1>
```
